# This is a basic workflow to help you get started with Actions

name: Refresh

on:
  #schedule:
  #- cron: "0 8 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip3 install -r requirements.txt
          python3 espresso_sales > sales.json
          mv sales.json ./docs/data/sales.json

      - uses: stefanzweifel/git-auto-commit-action@v4 
        with:
          file_pattern: ./docs/data/sales.json
